### ISSUE TITLE
problems with VS Code version 1.39.0

### ISSUE THREAD

**Issue by chriswe7374** [microsoft/azure-repos-vscode#570] opened 2019-10-10 07:32 UTC
No checkedout files shown anymore (only an empty page). Even the texts "included changes" "excluded changes" are missing. 
Working as expected after downgrade to vs code 1.38.1

**Comment by filippoitaliano** [comment] 2019-10-10 07:36
Same issue here. My colleague experienced the same problem on vscode insiders since last week. Blank page if there are changes.

**Comment by gulbaek** [comment] 2019-10-10 07:53
Same here after updating to 1.39.0

No information in
`Ctrl-shift-p` => `Show Logs` => `Extension Host`

Same goes for all files in
`%AppData%\Code\logs`

Tried deleting all files in, no luck
`%AppData%\Code\Cache`
`%AppData%\Code\CachedData`

**Comment by micheleberetta98** [comment] 2019-10-10 08:05
I am the colleague @filippoitaliano referenced and I can confirm.

**Comment by r-k-o-l** [comment] 2019-10-10 12:14
same issue here.

**Comment by waterkamp** [comment] 2019-10-10 13:39
same here! aiaiaiaiaiaiaiaiaiai....

**Comment by fredjeck** [comment] 2019-10-10 13:46
Same here, project seems to be connected (can click on the links in the status bar to open the project's page), the bookmark bar shows a notification with the number of pending changes but the pane is empty

**Comment by dragoljub** [comment] 2019-10-10 21:59
same here.

**Comment by dragoljub** [comment] 2019-10-10 22:59
I downgraded to 1.38.1 and can see pending changes now in TFVC.

**Comment by fchau-ralis** [comment] 2019-10-11 19:43
Same here. Please help! At least update the app so that it works properly! We're stuck with TFS so this is the only GUI solution i have on Mac.

**Comment by timdang** [comment] 2019-10-11 21:34
Latest commit to this project was back in March? so maybe this extension isn't well maintained anymore - which sucks, because `git tf` no longer works for me under Mac OS Catalina.

**Comment by joaomoreno** [comment] 2019-10-14 09:25
VS Code issue: https://github.com/microsoft/vscode/issues/82203

Fix is coming on the recovery release this week. Feel free to close this issue.

**Comment by dragoljub** [comment] 2019-10-14 18:15
Thanks 👍

**Comment by benshabatnoam** [comment] 2019-10-22 05:27
Just installed latest update of vs-code 1.39.2 and it is working. Thanks.

**Comment by gabomontero89** [comment] 2019-12-02 18:10
Hi guys.
I am facing the same issue but with VS Code `1.40.2`

OS: `v18.04.2`
![Screenshot_2019-12-02_13-05-29](https://user-images.githubusercontent.com/25494196/69983330-711d0080-1504-11ea-86a4-5015d5754b5c.png)

If I toggle `SCM` as some peoples say, but then this error shows up.
![Screenshot_2019-12-02_12-55-36](https://user-images.githubusercontent.com/25494196/69983378-901b9280-1504-11ea-9064-4a8fc2db1df7.png)

**The issue is still there with all extensions disabled.**

**Comment by benshabatnoam** [comment] 2019-12-02 18:13
I'm using the same version of vscode and I'm having no problems at all.
try the followings:
1. reset all of team settings.
2. if step 1 didn't work, try to re-install vscode.

**Comment by gabomontero89** [comment] 2019-12-02 18:34
> I'm using the same version of vscode and I'm having no problems at all.
> try the followings:
> 
> 1. reset all of team settings.
> 2. if step 1 didn't work, try to re-install vscode.

@benshabatnoam After a re-install is working again. Thanks.

**Closed** 2020-11-06 14:13 UTC
