### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ahrasel** [microsoft/azure-repos-vscode#505] opened 2019-04-04 07:42 UTC
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.149.2`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/winwinsp-se2/ms-vsts.team-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by lgp1985** [comment] 2019-07-03 17:49
Duplicate of #460

**Closed** 2020-08-10 16:43 UTC
