### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ProyectosCONSISS** [microsoft/azure-repos-vscode#491] opened 2019-02-27 15:31 UTC
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.149.2`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Consiss\ms-vsts.team-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by lgp1985** [comment] 2019-07-03 17:48
Duplicate of #460

**Closed** 2020-11-06 14:13 UTC
