### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by williamdekou** [Microsoft/azure-repos-vscode#481] opened 2019-02-11 12:04 UTC
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.144.1`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `~/ms-vsts.team-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jrbriggs** [comment] 2019-02-13 15:47
Dupe of #460

**Closed by jrbriggs** 2019-02-13 15:47 UTC
