### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by begunfx** [microsoft/azure-repos-vscode#520] opened 2019-05-11 17:00 UTC
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.149.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/begun/ms-vsts.team-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by begunfx** [comment] 2019-05-11 17:01
[ms-vsts.team-unresponsive.cpuprofile.txt](https://github.com/microsoft/azure-repos-vscode/files/3169275/ms-vsts.team-unresponsive.cpuprofile.txt)

**Comment by lgp1985** [comment] 2019-07-03 17:52
Duplicate of #460

**Closed** 2020-11-06 14:13 UTC
