### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by minchukm7** [Microsoft/azure-repos-vscode#462] opened 2019-01-10 23:21 UTC
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.144.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/mosesminchuk/ms-vsts.team-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jrbriggs** [comment] 2019-02-13 15:46
Dupe of #460

**Closed by jrbriggs** 2019-02-13 15:46 UTC
