### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nando-win** [Microsoft/azure-repos-vscode#482] opened 2019-02-12 00:03 UTC
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.144.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\nando\ms-vsts.team-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by nando-win** [comment] 2019-02-12 00:04
Just installing the extensions, and cpu was high loaded

**Comment by jrbriggs** [comment] 2019-02-13 15:47
Dupe of #460

**Closed by jrbriggs** 2019-02-13 15:47 UTC
