### ISSUE TITLE
TFVC Source Control Viewlet Sync Error - (team) You are signed out. Please run the 'team signin' command.

### ISSUE THREAD

**Issue by gmrscott** [microsoft/azure-repos-vscode#476] opened 2019-02-05 23:30 UTC
<h2>Steps to reproduce</h2>

1. Connect to an **Azure DevOps Services Repo** via the `Team: Signin` command and the `Authenticate and get an access token automatically (new experience)` option.

2. Open the local **TFVC Repository** folder of a team project and verify that **Azure Repos** detects the project by the fact that the indicator changes from `Team (i)` to the project's name.

3. Open the **TFVC Source Control Viewlet** and verify that you are able to see all included and excluded changes. 

4. Inside the viewlet, click the `'...' Menu` followed by the `Sync` option.

5. In the bottom right corner, you will see the following error notification: `(team) You are signed out. Please run the 'team signin' command.`

I receive this error every single time I try to Sync. If I am unable to pull down my team members' changes, this extension becomes darn near completely useless for me and my team.

Any thoughts?

<br />

<h2>Technical Details</h2>

<h3>Visual Studio Code</h3>

Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

<h3>Azure Repos Extension</h3>

Version: v1.144.1 (2018-11-05)

**Comment by filippoitaliano** [comment] 2019-02-07 08:01
Same problem.

## Technical Details
Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

### Azure Repos Extension
Version: v1.144.1 (2018-11-05)

**Comment by jurual** [comment] 2019-02-07 09:35
Same problem, since installing Visual Studio 2019 preview

**Comment by borjapuerta** [comment] 2019-02-07 12:29
Same problem with VSCode:
Error message: Unauthorized. Check your authentication credentials and try again.

VSCode Versión: 1.31.0 (user setup)
Azure Repos Extension Version: v1.144.1

I have Visual Studio 2017 installed at my computer.

**Comment by filippoitaliano** [comment] 2019-02-07 14:37
The problem is some change inside vscode@1.31.
[https://github.com/Microsoft/azure-repos-vscode/issues/477l](https://github.com/Microsoft/azure-repos-vscode/issues/477l)

A workaround is to install vscode@1.30 [https://code.visualstudio.com/updates/v1_30](https://code.visualstudio.com/updates/v1_30)
and disable auto update for now [https://stackoverflow.com/questions/50162685/how-do-i-disable-vs-code-of-updating-itself](https://stackoverflow.com/questions/50162685/how-do-i-disable-vs-code-of-updating-itself)

**Comment by ewaschenko** [comment] 2019-02-07 15:17
Can't login, getting the error

> Unauthorized. Check your auth credentials and try again.

Happened as soon as I updated to 1.31.0

**Comment by gmrscott** [comment] 2019-02-07 17:28
> 
> 
> The problem is related to some change inside vscode@1.31.
> https://github.com/Microsoft/azure-repos-vscode/issues/477l
> 
> A workaround is to install vscode@1.30 https://code.visualstudio.com/updates/v1_30
> and disable auto update for now https://stackoverflow.com/questions/50162685/how-do-i-disable-vs-code-of-updating-itself

I am the OP and in the **Technical Details** portion of my post, you can see that the version where I experienced this issue was in fact **1.30.2**.

**Comment by dragoljub** [comment] 2019-02-07 23:16
I downgraded to VS Code 1.30.0: https://update.code.visualstudio.com/1.30.0/win32-x64-user/stable and now am able to connect to TFS with Azure Repos 1.144.1. Win 10 Enterprise.

**Comment by filippoitaliano** [comment] 2019-02-08 09:23
@gmrscott Sorry, you're right. This is strange, I'm using **vscode@1.30.2** and it works as usual.
I experienced the issue updating from 1.30.2 to 1.31.

**Comment by RCKSTR1** [comment] 2019-02-09 00:29
Happening to me too. Just after the January update :(

I'm running VSCode Jan2019 update and TEE-CLC-14.134.0 + The Azure Repos extension
on macOS High Sierra 10.13.6

I'm able to do get and checkin on the terminal, but not with the extension.

**Comment by mdschweda** [comment] 2019-02-11 09:30
Same problem here

```
Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

TFS 15.117.27414.0 (Tfs2017.Update3)
TF.exe 15.129.28306.1
```

**Comment by beyerleinf** [comment] 2019-02-11 10:37
Same Problem with the current insider build
```
Version: 1.32.0-insider
Commit: d049558486b5ccebc607c826ac4055970b0bc80e
Date: 2019-02-11T06:13:08.554Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64
```

**Comment by HackproTm** [comment] 2019-02-12 16:18
Same problem

Version: 1.31.0 (system setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.3.9600

**Comment by admir86** [comment] 2019-02-13 14:58
not resolved in 1.31.**1**

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.15063

**Comment by reinisbz** [comment] 2019-02-13 17:44
Same problem.

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

**Comment by dragoljub** [comment] 2019-02-14 17:53
Can someone on the latest version try changing the extension proxy settings to see if it fixes the issue for you?

![image](https://user-images.githubusercontent.com/2701562/52806553-26e29580-303e-11e9-9567-a55c9a710a3a.png)

**Comment by Larhei** [comment] 2019-02-14 17:58
@dragoljub Yes it fixes the issue for me on Mac latest VS Code Version

**Comment by beyerleinf** [comment] 2019-02-14 18:11
@dragoljub This fix also works for the latest stable and insiders build! Thanks! :)

**Comment by chrmarti** [comment] 2019-02-20 08:06
This should be fixed in current insiders builds of VS Code with the Proxy Support setting set to 'override'. Let me know if you still see any issues with that. Download: https://code.visualstudio.com/insiders/

**Comment by filippoitaliano** [comment] 2019-03-08 07:45
Is the issue fixed in [https://code.visualstudio.com/updates/v1_32](https://code.visualstudio.com/updates/v1_32)? I didn't tried yet.

**Comment by chrmarti** [comment] 2019-03-08 10:27
This should be fixed in 1.32 if you do *not* have a network proxy configured for the TFVC server.

If you do have a network proxy configured, you can try unsetting it by adding it to the `NO_PROXY` environment variable and giving the latest 1.33 Insiders build a try: https://code.visualstudio.com/insiders/ (feature request: https://github.com/Microsoft/vscode/issues/68260)

Let me know if that helps.

**Comment by filippoitaliano** [comment] 2019-03-08 11:01
Thanks! I don't have a network proxy configured for TFVC and the 1.32 works perfectly.

**Comment by onelifenyc** [comment] 2020-07-24 01:48
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Can someone help out - this started happening recently. See GIF. 

(ISSUE:  "Exclude" and it gets added back. Also, after that even DIFF would not work and keep prompting me to run 'team signin' but I am signed-in just fine)

![issue with vscode and azure repos ext](https://user-images.githubusercontent.com/4038782/88354233-4a7b3680-cd2e-11ea-931f-d0433d28f01c.gif)

**Comment by dragoljub** [comment] 2020-07-24 04:01
I’m seeing similar issues through my company VPN. Sometimes when I click on a pending change it takes 3 rounds of asking me to sign in. I just keep clicking until the diff finally shows up. I don’t actually have to sign in more than once. TFVC Win 10 latest VS code x64.

**Comment by dragoljub** [comment] 2020-07-24 23:57
I'm actually seeing this same thing now. It seems like TFVC plugin is logging in and out in a loop over and over.

**Closed** 2020-11-06 14:13 UTC
