### ISSUE TITLE
TFVC errors (via stderr): TF30063: You are not authorized to access

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/azure-repos-vscode#322] opened 2017-10-03 02:59 UTC
I created a PAT, set the expiry code for1 year, everything is set, copied the code
when to vscode, typed f1, then team sign in, then selected 'provide an access...', pasted the PAT code, hit enter, i get a ! beside the word Team in status bar.. enabled logging, here is whats in the log

```
2017-10-03T02:57:57.911Z - debug:  [09676] TFVC errors (via stderr): TF30063: You are not authorized to access **workspace collection name removed**

2017-10-03T02:57:57.912Z - error:  [09676] Caught an exception during Tfvc SCM Provider initialization
2017-10-03T02:57:57.912Z - error:  [09676] It appears you are using a Server workspace. Currently, TFVC support is limited to Local workspaces. TF30063: You are not authorized to access **workspace collection name removed**
```

I have workspace set as local, no matter what i try todesn tseem to work

**Comment by kaylangan** [comment] 2017-11-08 22:23
Appears to be related to #325

**Comment by kaylangan** [comment] 2018-03-13 19:51
@zoinkydoink can you try the workaround suggested by NanFengCheong in #325 ?

**Comment by kaylangan** [comment] 2018-03-13 19:59
Closing as dupe of #325.

**Closed** 2020-11-06 14:14 UTC
Labels: duplicate
