### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by waellerbe** [microsoft/azure-repos-vscode#516] opened 2019-05-06 05:55 UTC
## Issue Submitted on Monday, 05/06/19
> Ran into an issue with an extension installed within the Visual Studio Code Editor

[ms-vsts.team-unresponsive.cpuprofile.txt](https://github.com/Microsoft/azure-repos-vscode/files/3146626/ms-vsts.team-unresponsive.cpuprofile.txt "File from my home directory")
- Issue Type: `Performance`
- Extension Name: `team`
- Extension Version: `1.149.2`
- OS Version: `Windows_NT x64 10.0.18885`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\lrbpr\ms-vsts.team-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by lgp1985** [comment] 2019-07-03 17:51
Duplicate of #460

**Comment by waellerbe** [comment] 2019-10-16 21:38
> "Duplicate of #460"  :  `Response from 07/03/19`

@lgp1985  Thank you for the feedback. 

Returning to VS Code, thanks to collaboration here in GitHub. ❗️

**Closed** 2020-11-06 14:13 UTC
